//! Setup wizard command

use anyhow::Result;
use clap::Args;
use console::style;
use inquire::{Confirm, Select};
// use masterm_core::config::{Config, ConfigLoader};
use super::output;

/// Setup command arguments
#[derive(Args)]
pub struct SetupArgs {
    /// Skip confirmation
    #[arg(long, short)]
    yes: bool,
}

/// Run the setup wizard
pub async fn run(_args: SetupArgs) -> Result<()> {
    output::header("MASTerm Setup Wizard");
    println!(
        "{}",
        style("Let's customize your terminal experience! 🎨").dim()
    );
    println!();

    // 1. Icons
    let icons = Select::new(
        "Do you want to enable Nerd Font icons?",
        vec![
            "Yes (I have a Nerd Font installed)",
            "No (Use Unicode symbols)",
            "No (Plain ASCII only)",
        ],
    )
    .with_help_message("Icons make the prompt look much better!")
    .prompt()?;

    let icon_mode = match icons {
        "Yes (I have a Nerd Font installed)" => "nerd",
        "No (Use Unicode symbols)" => "unicode",
        _ => "ascii",
    };

    // 2. Theme
    let theme = Select::new(
        "Choose your color theme:",
        vec![
            "Catppuccin (Soft Pastels)",
            "Dracula (Vibrant)",
            "Nord (Cool Ice)",
        ],
    )
    .prompt()?;

    let theme_mode = match theme {
        "Catppuccin (Soft Pastels)" => "catppuccin",
        "Dracula (Vibrant)" => "dracula",
        _ => "nord",
    };

    // 3. Safety Level
    let safety = Select::new(
        "Select your safety level:",
        vec![
            "Dev (Standard protection)",
            "Ops (High protection, confirm Dangerous cmds)",
            "Minimal (Fastest startup, fewer checks)",
        ],
    )
    .prompt()?;

    let safety_mode = match safety {
        "Ops (High protection, confirm Dangerous cmds)" => "ops",
        "Minimal (Fastest startup, fewer checks)" => "minimal",
        _ => "dev",
    };

    // 4. Cloud Sync
    let cloud = Confirm::new("Enable Cloud Sync backup?")
        .with_default(false)
        .with_help_message("Backs up config to GitHub Gist")
        .prompt()?;

    // Apply configuration
    output::header("Applying Changes");

    // In a real implementation we would load -> modify -> save.
    // Here we'll just indicate what we would do for now or write a simple file.
    let config_dir = dirs::home_dir().unwrap_or_default().join(".masterm.toml");

    // Construct the TOML string manually to preserve comments in a real scenario,
    // or use serde serialization. For this demo, simple string replacement/generation.

    let config_content = format!(
        r#"# MASTerm Configuration
# Generated by Setup Wizard

[core]
mode = "{}"

[prompt]
format = "powerline"
add_newline = true
left = ["directory", "git_branch", "git_status"]
right = ["cmd_duration", "time"]

[prompt.icons]
mode = "{}"

[prompt.colors]
theme = "{}"

[safety]
prod_detection = true
dangerous_commands = ["rm -rf", "DROP DATABASE"]

[sync]
enabled = {}
"#,
        safety_mode, icon_mode, theme_mode, cloud
    );

    std::fs::write(&config_dir, config_content)?;

    output::success("Configuration saved to ~/.masterm.toml");

    println!();
    println!(
        "Run {} to apply changes immediately.",
        style("exec $SHELL").cyan()
    );

    Ok(())
}
